### ISSUE TITLE
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated

### ISSUE THREAD

**Issue by si458** [iwittkau/minio-keygen#2]
is the any chance you could update the app to use the new variables?

maybe introduce an argument also to allow using the old legacy variables?

i keep getting a warning in the minio app saying
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
```

**Comment by iwittkau** [comment]
Thanks for reporting!

Please upgrade to [v0.2.0](https://github.com/iwittkau/minio-keygen/releases/tag/v0.2.0) and let me know if this works.

**Comment by si458** [comment]
@iwittkau works a treat!
thank you!
👍
